ocpp:
  enabled: true
  heartbeatInterval: 300
  connectionTimeout: 60

database:
  path: ems.db

websocket:
  username: user
  password: password

grid:
  type: P1HomeWizard
  gridType: Phase3_230V
  host: 192.168.129.17

devices:
  solar:
    - type: SMA_Sunny_Boy
      name: Sunny Boy 4
      host: 192.168.129.15
    - type: SMA_Sunny_Boy
      name: Sunny Boy 5
      host: 192.168.129.16
  heatPump:
    - type: DaikinHomeHub
      name: Daikin Altherma 3
      host: 192.168.129.12
  charger:
    - type: WebastoUnite
      name: Webasto Unite
      host: 192.168.129.19
      chargingCurrent:
        min: 6.0
        max: 32.0
  battery:
    - type: SMA_Sunny_Boy_Storage
      name: Home Battery
      host: 192.168.129.18

